'use client';
import { FormEvent, useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
type Task = { id:string; title:string; description:string|null; due_date:string|null; priority:string; status:string };
export function TasksPanel({weddingId}:{weddingId:string}) {
  const [items,setItems]=useState<Task[]>([]); const [editing,setEditing]=useState<Task|'new'|null>(null); const [filter,setFilter]=useState('Nyitott');
  async function load(){let query=supabase!.from('tasks').select('id,title,description,due_date,priority,status').eq('wedding_id',weddingId).order('due_date',{ascending:true,nullsFirst:false});if(filter==='Nyitott')query=query.neq('status','Elkészült');if(filter==='Elkészült')query=query.eq('status','Elkészült');const{data}=await query;setItems((data??[])as Task[])}
  useEffect(()=>{load();const timer=window.setInterval(load,30_000);return()=>window.clearInterval(timer)},[weddingId,filter]);
  async function toggle(task:Task){await supabase!.from('tasks').update({status:task.status==='Elkészült'?'Teendő':'Elkészült',updated_at:new Date().toISOString()}).eq('id',task.id);load()}
  return <section className="list-page"><div className="list-title"><div><p className="eyebrow">TERVEZÉS</p><h1>Teendők</h1></div><div className="list-actions"><strong>{items.length} db</strong><button onClick={()=>setEditing('new')}>＋</button></div></div><div className="filter-row">{['Nyitott','Mind','Elkészült'].map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value}</button>)}</div><div className="task-list full-list">{items.length?items.map(task=><article className="record-row" key={task.id}><button className={`check ${task.status==='Elkészült'?'checked':''}`} onClick={()=>toggle(task)}>{task.status==='Elkészült'?'✓':''}</button><button className="record-main" onClick={()=>setEditing(task)}><strong>{task.title}</strong><small>{task.due_date||'Nincs határidő'} · {task.priority} · {task.status}</small></button></article>):<p className="empty-list">Nincs megjeleníthető teendő.</p>}</div>{editing&&<Editor weddingId={weddingId} task={editing==='new'?null:editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);load()}}/>}</section>;
}
function Editor({weddingId,task,close,saved}:{weddingId:string;task:Task|null;close:()=>void;saved:()=>void}) {
  const [form,setForm]=useState({title:task?.title??'',description:task?.description??'',due_date:task?.due_date??'',priority:task?.priority??'Közepes',status:task?.status??'Teendő'}); const [error,setError]=useState('');
  async function submit(event:FormEvent){event.preventDefault();const payload={...form,due_date:form.due_date||null,description:form.description||null,updated_at:new Date().toISOString()};const result=task?await supabase!.from('tasks').update(payload).eq('id',task.id):await supabase!.from('tasks').insert({...payload,wedding_id:weddingId});if(result.error)setError(result.error.message);else saved()}
  return <div className="modal-backdrop"><section className="editor-card"><div className="editor-heading"><div><p className="eyebrow">TEENDŐ</p><h2>{task?'Szerkesztés':'Új teendő'}</h2></div><button onClick={close}>×</button></div><form onSubmit={submit}><label>Megnevezés<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>Leírás<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Határidő<input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><div className="form-row"><label>Prioritás<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Alacsony</option><option>Közepes</option><option>Magas</option></select></label><label>Állapot<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Teendő</option><option>Folyamatban</option><option>Elkészült</option></select></label></div>{error&&<p className="form-message">{error}</p>}<button className="primary-action">Mentés</button></form></section></div>;
}
